// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAvailabilityException = `-- name: CreateAvailabilityException :one
INSERT INTO availability_exceptions (business_id, rule_id, staff_id, occurrence_start, reason)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, business_id, rule_id, staff_id, occurrence_start, reason, created_at
`

type CreateAvailabilityExceptionParams struct {
	BusinessID      pgtype.UUID        `json:"business_id"`
	RuleID          pgtype.UUID        `json:"rule_id"`
	StaffID         pgtype.UUID        `json:"staff_id"`
	OccurrenceStart pgtype.Timestamptz `json:"occurrence_start"`
	Reason          pgtype.Text        `json:"reason"`
}

func (q *Queries) CreateAvailabilityException(ctx context.Context, arg CreateAvailabilityExceptionParams) (AvailabilityException, error) {
	row := q.db.QueryRow(ctx, createAvailabilityException,
		arg.BusinessID,
		arg.RuleID,
		arg.StaffID,
		arg.OccurrenceStart,
		arg.Reason,
	)
	var i AvailabilityException
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.RuleID,
		&i.StaffID,
		&i.OccurrenceStart,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createAvailabilityOverride = `-- name: CreateAvailabilityOverride :one
INSERT INTO availability_overrides (
  business_id, rule_id, staff_id, original_occurrence_start, new_start, new_end, capacity, is_closed, is_active
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, business_id, rule_id, staff_id, original_occurrence_start, new_start, new_end, capacity, is_closed, is_active, created_at, updated_at
`

type CreateAvailabilityOverrideParams struct {
	BusinessID              pgtype.UUID        `json:"business_id"`
	RuleID                  pgtype.UUID        `json:"rule_id"`
	StaffID                 pgtype.UUID        `json:"staff_id"`
	OriginalOccurrenceStart pgtype.Timestamptz `json:"original_occurrence_start"`
	NewStart                pgtype.Timestamptz `json:"new_start"`
	NewEnd                  pgtype.Timestamptz `json:"new_end"`
	Capacity                pgtype.Int4        `json:"capacity"`
	IsClosed                bool               `json:"is_closed"`
	IsActive                bool               `json:"is_active"`
}

func (q *Queries) CreateAvailabilityOverride(ctx context.Context, arg CreateAvailabilityOverrideParams) (AvailabilityOverride, error) {
	row := q.db.QueryRow(ctx, createAvailabilityOverride,
		arg.BusinessID,
		arg.RuleID,
		arg.StaffID,
		arg.OriginalOccurrenceStart,
		arg.NewStart,
		arg.NewEnd,
		arg.Capacity,
		arg.IsClosed,
		arg.IsActive,
	)
	var i AvailabilityOverride
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.RuleID,
		&i.StaffID,
		&i.OriginalOccurrenceStart,
		&i.NewStart,
		&i.NewEnd,
		&i.Capacity,
		&i.IsClosed,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAvailabilityRule = `-- name: CreateAvailabilityRule :one
INSERT INTO availability_rules (
  business_id, staff_id, rule_type, timezone, start_local, end_local, rrule, effective_from, effective_until, default_capacity
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, business_id, staff_id, rule_type, timezone, start_local, end_local, rrule, effective_from, effective_until, default_capacity, is_active, created_at, updated_at
`

type CreateAvailabilityRuleParams struct {
	BusinessID      pgtype.UUID      `json:"business_id"`
	StaffID         pgtype.UUID      `json:"staff_id"`
	RuleType        string           `json:"rule_type"`
	Timezone        string           `json:"timezone"`
	StartLocal      pgtype.Timestamp `json:"start_local"`
	EndLocal        pgtype.Timestamp `json:"end_local"`
	Rrule           string           `json:"rrule"`
	EffectiveFrom   pgtype.Date      `json:"effective_from"`
	EffectiveUntil  pgtype.Date      `json:"effective_until"`
	DefaultCapacity int32            `json:"default_capacity"`
}

func (q *Queries) CreateAvailabilityRule(ctx context.Context, arg CreateAvailabilityRuleParams) (AvailabilityRule, error) {
	row := q.db.QueryRow(ctx, createAvailabilityRule,
		arg.BusinessID,
		arg.StaffID,
		arg.RuleType,
		arg.Timezone,
		arg.StartLocal,
		arg.EndLocal,
		arg.Rrule,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.DefaultCapacity,
	)
	var i AvailabilityRule
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.StaffID,
		&i.RuleType,
		&i.Timezone,
		&i.StartLocal,
		&i.EndLocal,
		&i.Rrule,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.DefaultCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAvailabilityRuleService = `-- name: CreateAvailabilityRuleService :one
INSERT INTO availability_rule_services (rule_id, staff_id, service_id, capacity_override, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING rule_id, staff_id, service_id, capacity_override, is_active, created_at, updated_at
`

type CreateAvailabilityRuleServiceParams struct {
	RuleID           pgtype.UUID `json:"rule_id"`
	StaffID          pgtype.UUID `json:"staff_id"`
	ServiceID        pgtype.UUID `json:"service_id"`
	CapacityOverride pgtype.Int4 `json:"capacity_override"`
	IsActive         bool        `json:"is_active"`
}

func (q *Queries) CreateAvailabilityRuleService(ctx context.Context, arg CreateAvailabilityRuleServiceParams) (AvailabilityRuleService, error) {
	row := q.db.QueryRow(ctx, createAvailabilityRuleService,
		arg.RuleID,
		arg.StaffID,
		arg.ServiceID,
		arg.CapacityOverride,
		arg.IsActive,
	)
	var i AvailabilityRuleService
	err := row.Scan(
		&i.RuleID,
		&i.StaffID,
		&i.ServiceID,
		&i.CapacityOverride,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOverrideService = `-- name: CreateOverrideService :one
INSERT INTO override_services (override_id, service_id, is_active)
VALUES ($1,$2,$3)
RETURNING override_id, service_id, is_active, created_at
`

type CreateOverrideServiceParams struct {
	OverrideID pgtype.UUID `json:"override_id"`
	ServiceID  pgtype.UUID `json:"service_id"`
	IsActive   bool        `json:"is_active"`
}

func (q *Queries) CreateOverrideService(ctx context.Context, arg CreateOverrideServiceParams) (OverrideService, error) {
	row := q.db.QueryRow(ctx, createOverrideService, arg.OverrideID, arg.ServiceID, arg.IsActive)
	var i OverrideService
	err := row.Scan(
		&i.OverrideID,
		&i.ServiceID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getAvailabilityRuleByID = `-- name: GetAvailabilityRuleByID :one
SELECT id, business_id, staff_id, rule_type, timezone, start_local, end_local, rrule, effective_from, effective_until, default_capacity, is_active, created_at, updated_at FROM availability_rules WHERE id = $1
`

func (q *Queries) GetAvailabilityRuleByID(ctx context.Context, id pgtype.UUID) (AvailabilityRule, error) {
	row := q.db.QueryRow(ctx, getAvailabilityRuleByID, id)
	var i AvailabilityRule
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.StaffID,
		&i.RuleType,
		&i.Timezone,
		&i.StartLocal,
		&i.EndLocal,
		&i.Rrule,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.DefaultCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRulesForStaffServiceRange = `-- name: ListActiveRulesForStaffServiceRange :many
SELECT ar.id, ar.business_id, ar.staff_id, ar.rule_type, ar.timezone, ar.start_local, ar.end_local, ar.rrule, ar.effective_from, ar.effective_until, ar.default_capacity, ar.is_active, ar.created_at, ar.updated_at
FROM availability_rules ar
JOIN availability_rule_services ars
  ON ars.rule_id = ar.id
 AND ars.staff_id = ar.staff_id
WHERE ar.staff_id = $1
  AND ars.service_id = $2
  AND ar.is_active = TRUE
  AND ars.is_active = TRUE
  AND ar.effective_from <= $4::date
  AND (ar.effective_until IS NULL OR ar.effective_until >= $3::date)
ORDER BY ar.created_at DESC
`

type ListActiveRulesForStaffServiceRangeParams struct {
	StaffID   pgtype.UUID `json:"staff_id"`
	ServiceID pgtype.UUID `json:"service_id"`
	Column3   pgtype.Date `json:"column_3"`
	Column4   pgtype.Date `json:"column_4"`
}

func (q *Queries) ListActiveRulesForStaffServiceRange(ctx context.Context, arg ListActiveRulesForStaffServiceRangeParams) ([]AvailabilityRule, error) {
	rows, err := q.db.Query(ctx, listActiveRulesForStaffServiceRange,
		arg.StaffID,
		arg.ServiceID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityRule
	for rows.Next() {
		var i AvailabilityRule
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.StaffID,
			&i.RuleType,
			&i.Timezone,
			&i.StartLocal,
			&i.EndLocal,
			&i.Rrule,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.DefaultCapacity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityExceptionsByRuleRange = `-- name: ListAvailabilityExceptionsByRuleRange :many
SELECT id, business_id, rule_id, staff_id, occurrence_start, reason, created_at FROM availability_exceptions
WHERE rule_id = $1
  AND occurrence_start >= $2
  AND occurrence_start <= $3
ORDER BY occurrence_start
`

type ListAvailabilityExceptionsByRuleRangeParams struct {
	RuleID            pgtype.UUID        `json:"rule_id"`
	OccurrenceStart   pgtype.Timestamptz `json:"occurrence_start"`
	OccurrenceStart_2 pgtype.Timestamptz `json:"occurrence_start_2"`
}

func (q *Queries) ListAvailabilityExceptionsByRuleRange(ctx context.Context, arg ListAvailabilityExceptionsByRuleRangeParams) ([]AvailabilityException, error) {
	rows, err := q.db.Query(ctx, listAvailabilityExceptionsByRuleRange, arg.RuleID, arg.OccurrenceStart, arg.OccurrenceStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityException
	for rows.Next() {
		var i AvailabilityException
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.RuleID,
			&i.StaffID,
			&i.OccurrenceStart,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityOverridesByRuleRange = `-- name: ListAvailabilityOverridesByRuleRange :many
SELECT id, business_id, rule_id, staff_id, original_occurrence_start, new_start, new_end, capacity, is_closed, is_active, created_at, updated_at FROM availability_overrides
WHERE rule_id = $1
  AND is_active = TRUE
  AND original_occurrence_start >= $2
  AND original_occurrence_start <= $3
ORDER BY original_occurrence_start
`

type ListAvailabilityOverridesByRuleRangeParams struct {
	RuleID                    pgtype.UUID        `json:"rule_id"`
	OriginalOccurrenceStart   pgtype.Timestamptz `json:"original_occurrence_start"`
	OriginalOccurrenceStart_2 pgtype.Timestamptz `json:"original_occurrence_start_2"`
}

func (q *Queries) ListAvailabilityOverridesByRuleRange(ctx context.Context, arg ListAvailabilityOverridesByRuleRangeParams) ([]AvailabilityOverride, error) {
	rows, err := q.db.Query(ctx, listAvailabilityOverridesByRuleRange, arg.RuleID, arg.OriginalOccurrenceStart, arg.OriginalOccurrenceStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityOverride
	for rows.Next() {
		var i AvailabilityOverride
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.RuleID,
			&i.StaffID,
			&i.OriginalOccurrenceStart,
			&i.NewStart,
			&i.NewEnd,
			&i.Capacity,
			&i.IsClosed,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityRuleServicesByRule = `-- name: ListAvailabilityRuleServicesByRule :many
SELECT rule_id, staff_id, service_id, capacity_override, is_active, created_at, updated_at FROM availability_rule_services
WHERE rule_id = $1 AND ($2::bool = FALSE OR is_active = TRUE)
ORDER BY service_id
`

type ListAvailabilityRuleServicesByRuleParams struct {
	RuleID  pgtype.UUID `json:"rule_id"`
	Column2 bool        `json:"column_2"`
}

func (q *Queries) ListAvailabilityRuleServicesByRule(ctx context.Context, arg ListAvailabilityRuleServicesByRuleParams) ([]AvailabilityRuleService, error) {
	rows, err := q.db.Query(ctx, listAvailabilityRuleServicesByRule, arg.RuleID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityRuleService
	for rows.Next() {
		var i AvailabilityRuleService
		if err := rows.Scan(
			&i.RuleID,
			&i.StaffID,
			&i.ServiceID,
			&i.CapacityOverride,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityRulesByStaff = `-- name: ListAvailabilityRulesByStaff :many
SELECT id, business_id, staff_id, rule_type, timezone, start_local, end_local, rrule, effective_from, effective_until, default_capacity, is_active, created_at, updated_at FROM availability_rules
WHERE staff_id = $1 AND ($2::bool = FALSE OR is_active = TRUE)
ORDER BY created_at DESC
`

type ListAvailabilityRulesByStaffParams struct {
	StaffID pgtype.UUID `json:"staff_id"`
	Column2 bool        `json:"column_2"`
}

func (q *Queries) ListAvailabilityRulesByStaff(ctx context.Context, arg ListAvailabilityRulesByStaffParams) ([]AvailabilityRule, error) {
	rows, err := q.db.Query(ctx, listAvailabilityRulesByStaff, arg.StaffID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityRule
	for rows.Next() {
		var i AvailabilityRule
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.StaffID,
			&i.RuleType,
			&i.Timezone,
			&i.StartLocal,
			&i.EndLocal,
			&i.Rrule,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.DefaultCapacity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverrideServices = `-- name: ListOverrideServices :many
SELECT override_id, service_id, is_active, created_at FROM override_services
WHERE override_id = $1 AND is_active = TRUE
`

func (q *Queries) ListOverrideServices(ctx context.Context, overrideID pgtype.UUID) ([]OverrideService, error) {
	rows, err := q.db.Query(ctx, listOverrideServices, overrideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverrideService
	for rows.Next() {
		var i OverrideService
		if err := rows.Scan(
			&i.OverrideID,
			&i.ServiceID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleServicesByService = `-- name: ListRuleServicesByService :many
SELECT rule_id, staff_id, service_id, capacity_override, is_active, created_at, updated_at FROM availability_rule_services
WHERE service_id = $1 AND is_active = TRUE
ORDER BY staff_id
`

func (q *Queries) ListRuleServicesByService(ctx context.Context, serviceID pgtype.UUID) ([]AvailabilityRuleService, error) {
	rows, err := q.db.Query(ctx, listRuleServicesByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityRuleService
	for rows.Next() {
		var i AvailabilityRuleService
		if err := rows.Scan(
			&i.RuleID,
			&i.StaffID,
			&i.ServiceID,
			&i.CapacityOverride,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAvailabilityRuleServiceState = `-- name: SetAvailabilityRuleServiceState :exec
UPDATE availability_rule_services
SET is_active = $3
WHERE rule_id = $1 AND service_id = $2
`

type SetAvailabilityRuleServiceStateParams struct {
	RuleID    pgtype.UUID `json:"rule_id"`
	ServiceID pgtype.UUID `json:"service_id"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetAvailabilityRuleServiceState(ctx context.Context, arg SetAvailabilityRuleServiceStateParams) error {
	_, err := q.db.Exec(ctx, setAvailabilityRuleServiceState, arg.RuleID, arg.ServiceID, arg.IsActive)
	return err
}

const updateAvailabilityRule = `-- name: UpdateAvailabilityRule :one
UPDATE availability_rules
SET rule_type = $2,
    timezone = $3,
    start_local = $4,
    end_local = $5,
    rrule = $6,
    effective_from = $7,
    effective_until = $8,
    default_capacity = $9,
    is_active = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, business_id, staff_id, rule_type, timezone, start_local, end_local, rrule, effective_from, effective_until, default_capacity, is_active, created_at, updated_at
`

type UpdateAvailabilityRuleParams struct {
	ID              pgtype.UUID      `json:"id"`
	RuleType        string           `json:"rule_type"`
	Timezone        string           `json:"timezone"`
	StartLocal      pgtype.Timestamp `json:"start_local"`
	EndLocal        pgtype.Timestamp `json:"end_local"`
	Rrule           string           `json:"rrule"`
	EffectiveFrom   pgtype.Date      `json:"effective_from"`
	EffectiveUntil  pgtype.Date      `json:"effective_until"`
	DefaultCapacity int32            `json:"default_capacity"`
	IsActive        bool             `json:"is_active"`
}

func (q *Queries) UpdateAvailabilityRule(ctx context.Context, arg UpdateAvailabilityRuleParams) (AvailabilityRule, error) {
	row := q.db.QueryRow(ctx, updateAvailabilityRule,
		arg.ID,
		arg.RuleType,
		arg.Timezone,
		arg.StartLocal,
		arg.EndLocal,
		arg.Rrule,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.DefaultCapacity,
		arg.IsActive,
	)
	var i AvailabilityRule
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.StaffID,
		&i.RuleType,
		&i.Timezone,
		&i.StartLocal,
		&i.EndLocal,
		&i.Rrule,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.DefaultCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
