// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
RETURNING id, business_id, staff_id, customer_id, service_id, start_at, end_at, status, source_rule_id, source_override_id, created_at, updated_at
`

func (q *Queries) CancelBooking(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, cancelBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.StaffID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.SourceRuleID,
		&i.SourceOverrideID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  business_id, staff_id, customer_id, service_id, start_at, end_at, status, source_rule_id, source_override_id
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, business_id, staff_id, customer_id, service_id, start_at, end_at, status, source_rule_id, source_override_id, created_at, updated_at
`

type CreateBookingParams struct {
	BusinessID       pgtype.UUID        `json:"business_id"`
	StaffID          pgtype.UUID        `json:"staff_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	ServiceID        pgtype.UUID        `json:"service_id"`
	StartAt          pgtype.Timestamptz `json:"start_at"`
	EndAt            pgtype.Timestamptz `json:"end_at"`
	Status           string             `json:"status"`
	SourceRuleID     pgtype.UUID        `json:"source_rule_id"`
	SourceOverrideID pgtype.UUID        `json:"source_override_id"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.BusinessID,
		arg.StaffID,
		arg.CustomerID,
		arg.ServiceID,
		arg.StartAt,
		arg.EndAt,
		arg.Status,
		arg.SourceRuleID,
		arg.SourceOverrideID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.StaffID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.SourceRuleID,
		&i.SourceOverrideID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookingURL = `-- name: CreateBookingURL :one
INSERT INTO booking_urls (business_id, staff_id, slug, is_active)
VALUES ($1,$2,$3,$4)
RETURNING id, business_id, staff_id, slug, is_active, created_at
`

type CreateBookingURLParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	StaffID    pgtype.UUID `json:"staff_id"`
	Slug       string      `json:"slug"`
	IsActive   bool        `json:"is_active"`
}

func (q *Queries) CreateBookingURL(ctx context.Context, arg CreateBookingURLParams) (BookingUrl, error) {
	row := q.db.QueryRow(ctx, createBookingURL,
		arg.BusinessID,
		arg.StaffID,
		arg.Slug,
		arg.IsActive,
	)
	var i BookingUrl
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.StaffID,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getBookingURLBySlug = `-- name: GetBookingURLBySlug :one
SELECT id, business_id, staff_id, slug, is_active, created_at FROM booking_urls
WHERE slug = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetBookingURLBySlug(ctx context.Context, slug string) (BookingUrl, error) {
	row := q.db.QueryRow(ctx, getBookingURLBySlug, slug)
	var i BookingUrl
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.StaffID,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingURLsByBusiness = `-- name: ListBookingURLsByBusiness :many
SELECT id, business_id, staff_id, slug, is_active, created_at FROM booking_urls
WHERE business_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookingURLsByBusiness(ctx context.Context, businessID pgtype.UUID) ([]BookingUrl, error) {
	rows, err := q.db.Query(ctx, listBookingURLsByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingUrl
	for rows.Next() {
		var i BookingUrl
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.StaffID,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByBusinessRange = `-- name: ListBookingsByBusinessRange :many
SELECT id, business_id, staff_id, customer_id, service_id, start_at, end_at, status, source_rule_id, source_override_id, created_at, updated_at FROM bookings
WHERE business_id = $1
  AND ($2::bool = FALSE OR status = 'confirmed')
  AND end_at > $3
  AND start_at < $4
ORDER BY start_at
`

type ListBookingsByBusinessRangeParams struct {
	BusinessID pgtype.UUID        `json:"business_id"`
	Column2    bool               `json:"column_2"`
	EndAt      pgtype.Timestamptz `json:"end_at"`
	StartAt    pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) ListBookingsByBusinessRange(ctx context.Context, arg ListBookingsByBusinessRangeParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByBusinessRange,
		arg.BusinessID,
		arg.Column2,
		arg.EndAt,
		arg.StartAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.StaffID,
			&i.CustomerID,
			&i.ServiceID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.SourceRuleID,
			&i.SourceOverrideID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByStaffRange = `-- name: ListBookingsByStaffRange :many
SELECT id, business_id, staff_id, customer_id, service_id, start_at, end_at, status, source_rule_id, source_override_id, created_at, updated_at FROM bookings
WHERE staff_id = $1
  AND status = 'confirmed'
  AND end_at > $2
  AND start_at < $3
ORDER BY start_at
`

type ListBookingsByStaffRangeParams struct {
	StaffID pgtype.UUID        `json:"staff_id"`
	EndAt   pgtype.Timestamptz `json:"end_at"`
	StartAt pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) ListBookingsByStaffRange(ctx context.Context, arg ListBookingsByStaffRangeParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByStaffRange, arg.StaffID, arg.EndAt, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.StaffID,
			&i.CustomerID,
			&i.ServiceID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.SourceRuleID,
			&i.SourceOverrideID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
