// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (business_id, full_name, email, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, full_name, email, phone, is_active, created_at, updated_at
`

type CreateCustomerParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	FullName   string      `json:"full_name"`
	Email      pgtype.Text `json:"email"`
	Phone      pgtype.Text `json:"phone"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.BusinessID,
		arg.FullName,
		arg.Email,
		arg.Phone,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByBusinessEmail = `-- name: GetCustomerByBusinessEmail :one
SELECT id, business_id, full_name, email, phone, is_active, created_at, updated_at FROM customers
WHERE business_id = $1
  AND LOWER(TRIM(COALESCE(email::text, ''))) = LOWER(TRIM($2))
LIMIT 1
`

type GetCustomerByBusinessEmailParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Btrim      string      `json:"btrim"`
}

func (q *Queries) GetCustomerByBusinessEmail(ctx context.Context, arg GetCustomerByBusinessEmailParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByBusinessEmail, arg.BusinessID, arg.Btrim)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, business_id, full_name, email, phone, is_active, created_at, updated_at FROM customers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomersByBusiness = `-- name: ListCustomersByBusiness :many
SELECT id, business_id, full_name, email, phone, is_active, created_at, updated_at FROM customers
WHERE business_id = $1 AND ($2::bool = FALSE OR is_active = TRUE)
ORDER BY full_name
`

type ListCustomersByBusinessParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Column2    bool        `json:"column_2"`
}

func (q *Queries) ListCustomersByBusiness(ctx context.Context, arg ListCustomersByBusinessParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByBusiness, arg.BusinessID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET full_name = $2,
    email = $3,
    phone = $4,
    is_active = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, business_id, full_name, email, phone, is_active, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID       pgtype.UUID `json:"id"`
	FullName string      `json:"full_name"`
	Email    pgtype.Text `json:"email"`
	Phone    pgtype.Text `json:"phone"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.IsActive,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
