// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilityException struct {
	ID              pgtype.UUID        `json:"id"`
	BusinessID      pgtype.UUID        `json:"business_id"`
	RuleID          pgtype.UUID        `json:"rule_id"`
	StaffID         pgtype.UUID        `json:"staff_id"`
	OccurrenceStart pgtype.Timestamptz `json:"occurrence_start"`
	Reason          pgtype.Text        `json:"reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AvailabilityOverride struct {
	ID                      pgtype.UUID        `json:"id"`
	BusinessID              pgtype.UUID        `json:"business_id"`
	RuleID                  pgtype.UUID        `json:"rule_id"`
	StaffID                 pgtype.UUID        `json:"staff_id"`
	OriginalOccurrenceStart pgtype.Timestamptz `json:"original_occurrence_start"`
	NewStart                pgtype.Timestamptz `json:"new_start"`
	NewEnd                  pgtype.Timestamptz `json:"new_end"`
	Capacity                pgtype.Int4        `json:"capacity"`
	IsClosed                bool               `json:"is_closed"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type AvailabilityRule struct {
	ID              pgtype.UUID        `json:"id"`
	BusinessID      pgtype.UUID        `json:"business_id"`
	StaffID         pgtype.UUID        `json:"staff_id"`
	RuleType        string             `json:"rule_type"`
	Timezone        string             `json:"timezone"`
	StartLocal      pgtype.Timestamp   `json:"start_local"`
	EndLocal        pgtype.Timestamp   `json:"end_local"`
	Rrule           string             `json:"rrule"`
	EffectiveFrom   pgtype.Date        `json:"effective_from"`
	EffectiveUntil  pgtype.Date        `json:"effective_until"`
	DefaultCapacity int32              `json:"default_capacity"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AvailabilityRuleService struct {
	RuleID           pgtype.UUID        `json:"rule_id"`
	StaffID          pgtype.UUID        `json:"staff_id"`
	ServiceID        pgtype.UUID        `json:"service_id"`
	CapacityOverride pgtype.Int4        `json:"capacity_override"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Booking struct {
	ID               pgtype.UUID        `json:"id"`
	BusinessID       pgtype.UUID        `json:"business_id"`
	StaffID          pgtype.UUID        `json:"staff_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	ServiceID        pgtype.UUID        `json:"service_id"`
	StartAt          pgtype.Timestamptz `json:"start_at"`
	EndAt            pgtype.Timestamptz `json:"end_at"`
	Status           string             `json:"status"`
	SourceRuleID     pgtype.UUID        `json:"source_rule_id"`
	SourceOverrideID pgtype.UUID        `json:"source_override_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type BookingUrl struct {
	ID         pgtype.UUID        `json:"id"`
	BusinessID pgtype.UUID        `json:"business_id"`
	StaffID    pgtype.UUID        `json:"staff_id"`
	Slug       string             `json:"slug"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BootstrapMarker struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Business struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Timezone  string             `json:"timezone"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID         pgtype.UUID        `json:"id"`
	BusinessID pgtype.UUID        `json:"business_id"`
	FullName   string             `json:"full_name"`
	Email      pgtype.Text        `json:"email"`
	Phone      pgtype.Text        `json:"phone"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type OverrideService struct {
	OverrideID pgtype.UUID        `json:"override_id"`
	ServiceID  pgtype.UUID        `json:"service_id"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID                  pgtype.UUID        `json:"id"`
	BusinessID          pgtype.UUID        `json:"business_id"`
	Name                string             `json:"name"`
	DurationMinutes     int32              `json:"duration_minutes"`
	BufferBeforeMinutes int32              `json:"buffer_before_minutes"`
	BufferAfterMinutes  int32              `json:"buffer_after_minutes"`
	DefaultCapacity     int32              `json:"default_capacity"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ServiceDuration struct {
	ID              pgtype.UUID        `json:"id"`
	ServiceID       pgtype.UUID        `json:"service_id"`
	DurationMinutes int32              `json:"duration_minutes"`
	PriceCents      pgtype.Int4        `json:"price_cents"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Staff struct {
	ID          pgtype.UUID        `json:"id"`
	BusinessID  pgtype.UUID        `json:"business_id"`
	DisplayName string             `json:"display_name"`
	Email       pgtype.Text        `json:"email"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type StaffService struct {
	StaffID   pgtype.UUID        `json:"staff_id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
