// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelBooking(ctx context.Context, id pgtype.UUID) (Booking, error)
	CreateAvailabilityException(ctx context.Context, arg CreateAvailabilityExceptionParams) (AvailabilityException, error)
	CreateAvailabilityOverride(ctx context.Context, arg CreateAvailabilityOverrideParams) (AvailabilityOverride, error)
	CreateAvailabilityRule(ctx context.Context, arg CreateAvailabilityRuleParams) (AvailabilityRule, error)
	CreateAvailabilityRuleService(ctx context.Context, arg CreateAvailabilityRuleServiceParams) (AvailabilityRuleService, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateBookingURL(ctx context.Context, arg CreateBookingURLParams) (BookingUrl, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOverrideService(ctx context.Context, arg CreateOverrideServiceParams) (OverrideService, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateServiceDuration(ctx context.Context, arg CreateServiceDurationParams) (ServiceDuration, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	DeleteServiceDuration(ctx context.Context, id pgtype.UUID) error
	DeleteServiceDurationsByService(ctx context.Context, serviceID pgtype.UUID) error
	GetAvailabilityRuleByID(ctx context.Context, id pgtype.UUID) (AvailabilityRule, error)
	GetBookingURLBySlug(ctx context.Context, slug string) (BookingUrl, error)
	GetCustomerByBusinessEmail(ctx context.Context, arg GetCustomerByBusinessEmailParams) (Customer, error)
	GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error)
	GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error)
	GetStaffByID(ctx context.Context, id pgtype.UUID) (Staff, error)
	ListActiveRulesForStaffServiceRange(ctx context.Context, arg ListActiveRulesForStaffServiceRangeParams) ([]AvailabilityRule, error)
	ListAvailabilityExceptionsByRuleRange(ctx context.Context, arg ListAvailabilityExceptionsByRuleRangeParams) ([]AvailabilityException, error)
	ListAvailabilityOverridesByRuleRange(ctx context.Context, arg ListAvailabilityOverridesByRuleRangeParams) ([]AvailabilityOverride, error)
	ListAvailabilityRuleServicesByRule(ctx context.Context, arg ListAvailabilityRuleServicesByRuleParams) ([]AvailabilityRuleService, error)
	ListAvailabilityRulesByStaff(ctx context.Context, arg ListAvailabilityRulesByStaffParams) ([]AvailabilityRule, error)
	ListBookingURLsByBusiness(ctx context.Context, businessID pgtype.UUID) ([]BookingUrl, error)
	ListBookingsByBusinessRange(ctx context.Context, arg ListBookingsByBusinessRangeParams) ([]Booking, error)
	ListBookingsByStaffRange(ctx context.Context, arg ListBookingsByStaffRangeParams) ([]Booking, error)
	ListCustomersByBusiness(ctx context.Context, arg ListCustomersByBusinessParams) ([]Customer, error)
	ListOverrideServices(ctx context.Context, overrideID pgtype.UUID) ([]OverrideService, error)
	ListRuleServicesByService(ctx context.Context, serviceID pgtype.UUID) ([]AvailabilityRuleService, error)
	ListServiceDurations(ctx context.Context, serviceID pgtype.UUID) ([]ServiceDuration, error)
	ListServicesByBusiness(ctx context.Context, arg ListServicesByBusinessParams) ([]Service, error)
	ListServicesByStaff(ctx context.Context, arg ListServicesByStaffParams) ([]Service, error)
	ListStaffByBusiness(ctx context.Context, arg ListStaffByBusinessParams) ([]Staff, error)
	// Staff who can offer this service: explicit staff_services link, or an active
	// availability rule that includes the service (open hours), or an active
	// availability override scoped to the service.
	ListStaffByService(ctx context.Context, arg ListStaffByServiceParams) ([]Staff, error)
	SetAvailabilityRuleServiceState(ctx context.Context, arg SetAvailabilityRuleServiceStateParams) error
	UpdateAvailabilityRule(ctx context.Context, arg UpdateAvailabilityRuleParams) (AvailabilityRule, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateServiceDuration(ctx context.Context, arg UpdateServiceDurationParams) (ServiceDuration, error)
	UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error)
}

var _ Querier = (*Queries)(nil)
