// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_durations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceDuration = `-- name: CreateServiceDuration :one
INSERT INTO service_durations (service_id, duration_minutes, price_cents, is_active)
VALUES ($1, $2, $3, TRUE)
RETURNING id, service_id, duration_minutes, price_cents, is_active, created_at
`

type CreateServiceDurationParams struct {
	ServiceID       pgtype.UUID `json:"service_id"`
	DurationMinutes int32       `json:"duration_minutes"`
	PriceCents      pgtype.Int4 `json:"price_cents"`
}

func (q *Queries) CreateServiceDuration(ctx context.Context, arg CreateServiceDurationParams) (ServiceDuration, error) {
	row := q.db.QueryRow(ctx, createServiceDuration, arg.ServiceID, arg.DurationMinutes, arg.PriceCents)
	var i ServiceDuration
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.DurationMinutes,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServiceDuration = `-- name: DeleteServiceDuration :exec
UPDATE service_durations SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeleteServiceDuration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServiceDuration, id)
	return err
}

const deleteServiceDurationsByService = `-- name: DeleteServiceDurationsByService :exec
UPDATE service_durations SET is_active = FALSE WHERE service_id = $1
`

func (q *Queries) DeleteServiceDurationsByService(ctx context.Context, serviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServiceDurationsByService, serviceID)
	return err
}

const listServiceDurations = `-- name: ListServiceDurations :many
SELECT id, service_id, duration_minutes, price_cents, is_active, created_at FROM service_durations
WHERE service_id = $1 AND is_active = TRUE
ORDER BY duration_minutes
`

func (q *Queries) ListServiceDurations(ctx context.Context, serviceID pgtype.UUID) ([]ServiceDuration, error) {
	rows, err := q.db.Query(ctx, listServiceDurations, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDuration
	for rows.Next() {
		var i ServiceDuration
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.DurationMinutes,
			&i.PriceCents,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceDuration = `-- name: UpdateServiceDuration :one
UPDATE service_durations
SET duration_minutes = $2,
    price_cents = $3,
    is_active = $4
WHERE id = $1
RETURNING id, service_id, duration_minutes, price_cents, is_active, created_at
`

type UpdateServiceDurationParams struct {
	ID              pgtype.UUID `json:"id"`
	DurationMinutes int32       `json:"duration_minutes"`
	PriceCents      pgtype.Int4 `json:"price_cents"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) UpdateServiceDuration(ctx context.Context, arg UpdateServiceDurationParams) (ServiceDuration, error) {
	row := q.db.QueryRow(ctx, updateServiceDuration,
		arg.ID,
		arg.DurationMinutes,
		arg.PriceCents,
		arg.IsActive,
	)
	var i ServiceDuration
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.DurationMinutes,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
