// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (business_id, name, duration_minutes, buffer_before_minutes, buffer_after_minutes, default_capacity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, name, duration_minutes, buffer_before_minutes, buffer_after_minutes, default_capacity, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	BusinessID          pgtype.UUID `json:"business_id"`
	Name                string      `json:"name"`
	DurationMinutes     int32       `json:"duration_minutes"`
	BufferBeforeMinutes int32       `json:"buffer_before_minutes"`
	BufferAfterMinutes  int32       `json:"buffer_after_minutes"`
	DefaultCapacity     int32       `json:"default_capacity"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.BusinessID,
		arg.Name,
		arg.DurationMinutes,
		arg.BufferBeforeMinutes,
		arg.BufferAfterMinutes,
		arg.DefaultCapacity,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.DurationMinutes,
		&i.BufferBeforeMinutes,
		&i.BufferAfterMinutes,
		&i.DefaultCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, business_id, name, duration_minutes, buffer_before_minutes, buffer_after_minutes, default_capacity, is_active, created_at, updated_at FROM services WHERE id = $1 LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.DurationMinutes,
		&i.BufferBeforeMinutes,
		&i.BufferAfterMinutes,
		&i.DefaultCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServicesByBusiness = `-- name: ListServicesByBusiness :many
SELECT id, business_id, name, duration_minutes, buffer_before_minutes, buffer_after_minutes, default_capacity, is_active, created_at, updated_at FROM services
WHERE business_id = $1 AND ($2::bool = FALSE OR is_active = TRUE)
ORDER BY name
`

type ListServicesByBusinessParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Column2    bool        `json:"column_2"`
}

func (q *Queries) ListServicesByBusiness(ctx context.Context, arg ListServicesByBusinessParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByBusiness, arg.BusinessID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.DurationMinutes,
			&i.BufferBeforeMinutes,
			&i.BufferAfterMinutes,
			&i.DefaultCapacity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByStaff = `-- name: ListServicesByStaff :many
SELECT s.id, s.business_id, s.name, s.duration_minutes, s.buffer_before_minutes, s.buffer_after_minutes, s.default_capacity, s.is_active, s.created_at, s.updated_at
FROM services s
JOIN staff_services ss ON ss.service_id = s.id
WHERE ss.staff_id = $1
  AND s.business_id = $2
  AND ss.is_active = TRUE
  AND s.is_active = TRUE
ORDER BY s.name
`

type ListServicesByStaffParams struct {
	StaffID    pgtype.UUID `json:"staff_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) ListServicesByStaff(ctx context.Context, arg ListServicesByStaffParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByStaff, arg.StaffID, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.DurationMinutes,
			&i.BufferBeforeMinutes,
			&i.BufferAfterMinutes,
			&i.DefaultCapacity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2,
    duration_minutes = $3,
    buffer_before_minutes = $4,
    buffer_after_minutes = $5,
    default_capacity = $6,
    is_active = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, business_id, name, duration_minutes, buffer_before_minutes, buffer_after_minutes, default_capacity, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	DurationMinutes     int32       `json:"duration_minutes"`
	BufferBeforeMinutes int32       `json:"buffer_before_minutes"`
	BufferAfterMinutes  int32       `json:"buffer_after_minutes"`
	DefaultCapacity     int32       `json:"default_capacity"`
	IsActive            bool        `json:"is_active"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.DurationMinutes,
		arg.BufferBeforeMinutes,
		arg.BufferAfterMinutes,
		arg.DefaultCapacity,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.DurationMinutes,
		&i.BufferBeforeMinutes,
		&i.BufferAfterMinutes,
		&i.DefaultCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
