// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (business_id, display_name, email)
VALUES ($1, $2, $3)
RETURNING id, business_id, display_name, email, is_active, created_at, updated_at
`

type CreateStaffParams struct {
	BusinessID  pgtype.UUID `json:"business_id"`
	DisplayName string      `json:"display_name"`
	Email       pgtype.Text `json:"email"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff, arg.BusinessID, arg.DisplayName, arg.Email)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.DisplayName,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, business_id, display_name, email, is_active, created_at, updated_at FROM staff WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStaffByID(ctx context.Context, id pgtype.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.DisplayName,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaffByBusiness = `-- name: ListStaffByBusiness :many
SELECT id, business_id, display_name, email, is_active, created_at, updated_at FROM staff
WHERE business_id = $1 AND ($2::bool = FALSE OR is_active = TRUE)
ORDER BY display_name
`

type ListStaffByBusinessParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Column2    bool        `json:"column_2"`
}

func (q *Queries) ListStaffByBusiness(ctx context.Context, arg ListStaffByBusinessParams) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffByBusiness, arg.BusinessID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.DisplayName,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffByService = `-- name: ListStaffByService :many
SELECT st.id, st.business_id, st.display_name, st.email, st.is_active, st.created_at, st.updated_at
FROM staff st
WHERE st.business_id = $2
  AND st.is_active = TRUE
  AND (
    EXISTS (
      SELECT 1 FROM staff_services ss
      WHERE ss.staff_id = st.id
        AND ss.service_id = $1
        AND ss.is_active = TRUE
    )
    OR EXISTS (
      SELECT 1 FROM availability_rule_services ars
      INNER JOIN availability_rules ar ON ar.id = ars.rule_id AND ar.staff_id = ars.staff_id
      WHERE ars.staff_id = st.id
        AND ars.service_id = $1
        AND ars.is_active = TRUE
        AND ar.is_active = TRUE
        AND ar.business_id = $2
    )
    OR EXISTS (
      SELECT 1
      FROM availability_overrides o
      JOIN override_services os ON os.override_id = o.id
      WHERE o.staff_id = st.id
        AND os.service_id = $1
        AND os.is_active = TRUE
        AND o.is_active = TRUE
        AND o.is_closed = FALSE
    )
  )
ORDER BY st.display_name
`

type ListStaffByServiceParams struct {
	ServiceID  pgtype.UUID `json:"service_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// Staff who can offer this service: explicit staff_services link, or an active
// availability rule that includes the service (open hours), or an active
// availability override scoped to the service.
func (q *Queries) ListStaffByService(ctx context.Context, arg ListStaffByServiceParams) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffByService, arg.ServiceID, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.DisplayName,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE staff
SET display_name = $2,
    email = $3,
    is_active = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, business_id, display_name, email, is_active, created_at, updated_at
`

type UpdateStaffParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Email       pgtype.Text `json:"email"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.IsActive,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.DisplayName,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
